### ISSUE TITLE
Adding Julia to benchmark

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#116]
Could we add Julia code timing to benchmark figure?  Would have to run on same CPU.

**Comment by ericagol** [comment]
Also, it might be interesting to add a comparison to george/HODLR so that others will know whether/why it's worthwhile to switch from george to celerite.

**Comment by dfm** [comment]
I'm hesitant to add this to the paper because I think that it would add more clutter without adding much. I'll add a sentence to the (currently non-existent) "performance" section to say that we get similar performance in all the implementations.

That being said, I do think that it's a good idea to add a Julia benchmark to the docs so perhaps you could make an IJulia notebook in the `docs/_static/notebooks` directory that makes this?
