### ISSUE TITLE
small numbers

### ISSUE THREAD

**Issue by susana98** [dfm/celerite#127]
Thanks for sharing this code, it is amazingly fast.
I am fitting a granulation model to Kepler light curve and it works if the flux is in ppm but not with the traditional normalisation to 1  for transit analysis. (What I mean is that it converges to different values or doesn't converge at all.)
Is this expected?
It is easily fixable by using ppm and changing the transit model accordingly but I would like to know if this is normal or if maybe I am doing something wrong.

Thanks a lot

**Comment by dfm** [comment]
I assume that you're talking about optimization when you say "converged" here because celerite doesn't have any iterative methods included. Optimization algorithms are very sensitive to changes in parameterization or units so you're probably not doing anything wrong and there probably isn't a bug. I always recommend trying to choose units where the variance of the signal, the error bars, and the parameters are all vaguely of order between ~1 and ~1e3 because this will tend to give you the best numerical performance.

I would expect something like MCMC sampling to give similar results regardless of the units because it should be less sensitive to these results, but that will only be true within reason...

**Comment by susana98** [comment]
ok. thank you very much.
