### ISSUE TITLE
Different types of Rotation Kernels

### ISSUE THREAD

**Issue by victoriafoing** [dfm/celerite#151]
Hi, 

I am interested in measuring the rotation periods of stars with celerite.
I noticed that there are different rotation kernels that can be used:

1. The rotation kernel from the celerite paper:
![image](https://user-images.githubusercontent.com/28833172/88190580-bc725380-cc3a-11ea-9f99-25b777f0dd14.png)
![image](https://user-images.githubusercontent.com/28833172/88190844-0fe4a180-cc3b-11ea-94c6-5a41d2108b8b.png)

2. The rotation kernel from the exoplanet toolkit:
![image](https://user-images.githubusercontent.com/28833172/88190635-cd22c980-cc3a-11ea-84e8-33faa65caf4b.png)

What are the advantages and disadvantages of each rotation kernel? Do they yield the same results?

**Comment by dfm** [comment]
The one from the original paper is not recommended. The one in exoplanet is a much better model and it's been used for this purpose in a handful of papers including https://arxiv.org/abs/1911.09705 and https://arxiv.org/abs/1910.04563

**Comment by ericagol** [comment]
Nice!

**Comment by ericagol** [comment]
@dfm  This might be good to add to celerity repo, along with adding the references to the exoplanet docs.

**Comment by dfm** [comment]
@ericagol: At this point I'm not going to add an implementation here because I'm working on a re-write: https://github.com/dfm/celerite2

The better kernel is already implemented there: https://github.com/dfm/celerite2/blob/main/python/celerite2/terms.py#L486

(as well as exposure time integration and various other new things that we've learned!)

**Comment by StephanStock** [comment]
> The one from the original paper is not recommended. The one in exoplanet is a much better model and it's been used for this purpose in a handful of papers including https://arxiv.org/abs/1911.09705 and https://arxiv.org/abs/1910.04563

Hi, 

Could you comment on why the celerite approximation to the QP kernel is not recommended? So far I worked with the george QP kernel and  I would love to switch to the celerite approximation, as it is significantly faster! However, the likelihoods of the posterior samples (and as a result also the log-evidence) was always significantly worse than for the george QP kernel. Is there some issue with the kernel?  Would you always prefer the SHO kernel when fitting RVs with planets and stellar activity?

Also I have a problem of interpreting and choosing the right prior for C. For the moment I use a wide Jeffreys from 1e-5 to 1e5. Can C be regarded similar as Gamma (harmonic complexity) in the QP-kernel?

**Comment by dfm** [comment]
The kernel from the original paper is by no means an approximation to an exp-sine-squared kernel! It was just meant as a made up example of something that one could choose. I've found that, in practice, it doesn't perform as well as the `RotationTerm` that I discuss and reference in the papers linked here. I'd definitely recommend a mixture of SHOs (as implemented by the `RotationTerm` or otherwise) for RVs too.

Also: the original kernel is not formally positive definite so you can end up with some serious numerical issues! For any specific application, it is worth experimenting with various options, but I definitely haven't found a case where some combination of `SHOTerms` isn't just as good as any other standard kernel.

**Comment by StephanStock** [comment]
Hi,
thanks for the quick reply! 
In the original paper you wrote that you "construct a simple celerite covariance function with similar properties" and that it "can be used as a drop-in replacement for a significant gain in computational efficiency". 

This made me think that it could be used as a faster replacement of the Exp-sine-squared-kernel. It is also advocated as such in the juliet paper which is the tool I mainly use. 
I will try out the simple SHO term then.

Best,
Stephan

**Comment by dfm** [comment]
@StephanStock: excellent. Happy to help if you run into issues.
