### ISSUE TITLE
Consider definitions of S_0

### ISSUE THREAD

**Issue by dfm** [dfm/celerite#44]
See #43.

The peak amplitude of the SHO model is currently a function of Q. This introduces covariances between Q and S_0 so it might be better to re-define as:

`S_0 -> S_0 * (4*Q^2 - 1) / (4*Q^4)`

or simply

`S_0 -> S_0 / Q^2`

**Comment by ericagol** [comment]
How about we parameterize with:

A = S_0*Q^2/(1-1/4/Q^2)*\omega_0^2
B = \omega_0/(2*Q)*\sqrt{\frac{1-1/4/Q^2}{1-1/2/Q^2}}
C = \sqrt{1-1/2/Q^2}*\omega_0

for Q > 1/\sqrt{2}.

Then, the Taylor expansion near the peak of the PSD is approximately:
A/(1+(\omega-C)^2/B^2)

so that A = peak amplitude where \omega = C and B = width.

These are the three quantities that may be best constrained by the data when there is a well-defined peak in the power spectrum, which I suspect should be fairly uncorrelated?

Then, we can invert this parameterization with:

Q = \sqrt{\frac{1}{2} + \frac{C^2}{8*B^2} \left(1 + \sqrt{1+B^2/C^2}\right)}

\omega_0 = C/\sqrt{1-1/2/Q^2}

S_0 = A*(1-1/4/Q^2)/(Q^2*\omega_0^2)

This seems rather complicated, but might do the trick.

I guess the other way to look at this is through the kernel approximation, equation (36).  The decay rate & period will be constrained by the shape of the kernel;  but will these be covariant if we don't use the above parameterization?

-Eric

**Comment by dfm** [comment]
I'm going to close this as a wontfix for the paper but we can return to it later when we apply this model in real life :-)
