### ISSUE TITLE
Figure 7 high frequency noise

### ISSUE THREAD

**Issue by ericagol** [dfm/celerite#56]
Figure 7 seems to show high-frequency correlated noise in the maximum likelihood model plotted in the top panel.  I'm wondering if this is due to the fact that the rotation kernel, equation (63), has a non-zero derivative at zero time-lag.  One possibility would be to replace the exp(-c*\tau) term with the approximate Matern-3/2 term,  c/(c-z)*exp(-z*\tau)-z/(c-z)*exp(-c*\tau), with, say, z ~ 0.99 c.  Of course this would slow down the solver by a factor of ~4 since J would be doubled.  Is this just an aesthetic issue, or is this trading off with some of the white noise?

**Comment by dfm** [comment]
I'm also fitting for a white noise component in this example. It does seem to be consistently non-zero but it's not plotted in the blue line so any "noise" that you see is due to the kernel choice. I'm not really worried about this in this example because it's just an effective model of the variability. If I was to use this for a result, I would definitely experiment with other kernels like you suggest. I don't think that that's needed for this paper.

**Comment by ericagol** [comment]
I would worry most about whether this would affect the timing precision & impact parameter since the timescale of ingress/egress is short.  But, yes, I'm fine leaving this example as is for the paper.
